In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv("D:\\Studies\\DS\\py-master\\ML\\14_naive_bayes\\spam.csv")

In [3]:
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
data.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [5]:
df=data

In [6]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [7]:
df.head(3)

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1

In [8]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(df['Message'],df['spam'],test_size=0.2)

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [29]:
x_count=cv.fit_transform(x_train.values)

In [30]:
a=x_count.toarray()[0]

In [31]:
len(a)

7757

In [32]:
from sklearn.naive_bayes import MultinomialNB
model= MultinomialNB()

In [33]:
model.fit(x_count,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
x_tes_count=cv.transform(x_test)

In [35]:
model.score(x_tes_count,y_test)

0.9856502242152466

In [37]:
model.predict(x_tes_count[:10])

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [38]:
y_test[:10]

3796    0
3779    0
4209    0
4701    1
1196    1
4885    0
2843    0
692     0
483     0
3525    0
Name: spam, dtype: int64

In [48]:
emails=['Hey hurry upto 50% discount on TV exculsive offer for you dont miss this.!','Hey Suren, will go to beach together tomorrow..?']

In [49]:
email_cont=cv.transform(emails)

In [50]:
model.predict(email_cont)

array([1, 0], dtype=int64)

In [52]:
from sklearn.pipeline import Pipeline
pp=Pipeline([
    ('verctorizer',CountVectorizer()),('nb',MultinomialNB())
])

In [53]:
pp.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('verctorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [54]:
pp.predict(emails)

array([1, 0], dtype=int64)

In [55]:
pp.score(x_test,y_test)

0.9856502242152466

In [56]:
emails

['Hey hurry upto 50% discount on TV exculsive offer for you dont miss this.!',
 'Hey Suren, will go to beach together tomorrow..?']